name=Arduino-Emulator-Target
version=0.0.2
author=Phil Schatzmann
maintainer=Phil Schatzmann
sentence=Execution target for Arduino-Emulator over stream or UDP transport.
paragraph=Provides command handling and hardware service tunneling for GPIO, SPI and Serial operations used by Arduino-Emulator.
category=Communication
url=https://github.com/pschatzmann/Arduino-Emulator-Target
architectures=*